chore: add brew version check to CI refactor: simplify formulae list handling in test_install_clean test: add formulae_list parameter to test_install_clean test: add git_dependencies parameter to test_update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -118,6 +118,7 @@ jobs:
         run: |
           # run brew update. It is needed especially on Ubuntu, otherwise parallel tests fails.
           brew update --force --quiet || true
+          brew --version
       - name: Set pseudo git user
         run: |
           git config --global user.name "runner"
@@ -179,6 +180,11 @@ jobs:
         with:
           pristine: true
           update: true
+      - name: Check Homebrew
+        run: |
+          # run brew update. It is needed especially on Ubuntu, otherwise parallel tests fails.
+          brew update --force --quiet || true
+          brew --version
       - name: Set pseudo git user
         run: |
           git config --global user.name "runner"
